[package]
name = "deadlock-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"
log = "0.4.22"
redis = { version = "0.27.6", features = ["aio", "tokio", "tokio-comp"] }
clap = { version = "4.5.23", features = ["env", "derive"] }
clickhouse = "0.13.1"
sqlx = { version = "0.8.2", features = ["macros", "postgres", "runtime-tokio", "uuid"] }
uuid = "1.11.0"
cached = { version = "0.54.0", features = ["async", "tokio"] }
axum = "0.7.9"
utoipa-axum = "0.1.2"
utoipa = { version = "5.2.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "8.0.3", features = ["axum"] }
serde = { version = "1.0.216", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde_json = "1.0.133"
url = "2.5.4"
