[package]
name = "deadlock-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"
log = "0.4.26"
redis = { version = "0.29.0", features = ["tokio-comp"] }
clap = { version = "4.5.30", features = ["env", "derive"] }
clickhouse = "0.13.1"
sqlx = { version = "0.8.3", features = ["macros", "postgres", "runtime-tokio", "uuid"] }
uuid = "1.14.0"
cached = { version = "0.54.0", features = ["async", "tokio"] }
axum = { version = "0.8.1", features = ["http2"] }
utoipa-axum = "0.2.0"
utoipa = { version = "5.3.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
serde = { version = "1.0.218", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde_json = "1.0.139"
url = "2.5.4"
derive_more = { version = "2.0.1", features = ["from"] }
object_store = { version = "0.11.2", features = ["aws"] }
tower = "0.5.2"
tower-layer = "0.3.3"
tower-service = "0.3.3"
tower-http = { version = "0.6.2", features = ["compression-full", "compression-zstd", "cors", "decompression-full", "trace"] }
tracing = "0.1.41"
