services:
  api:
    image: ghcr.io/deadlock-api/deadlock-api-rust/deadlock-api-rust:latest
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/v1/info/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
