[env]
_.file = '.env'

[tasks.load-test-env-vars]
run = ["export $(grep -v '^#' .env.testing| xargs) > /dev/null"]

[tasks.teardown-test-env]
run = ["docker compose -f docker-compose.testing.yaml down"]

[tasks.setup-test-env]
depends = ["teardown-test-env", "load-test-env-vars"]
run = ["docker compose -f docker-compose.testing.yaml up -d --wait"]

[tasks.test]
depends = ["setup-test-env"]
run = [
    "cargo test",
    "mise run teardown-test-env"
]
