name: Rust CI/CD

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to push (e.g., v1.0.0, specific-feature)'
        required: true
        type: string

env:
  RUST_TOOLCHAIN: stable
  CARGO_TERM_COLOR: always
  DEPOT_PROJECT_ID: k7kl7zsmcs
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  CARGO_INCREMENTAL: 0

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test_deploy:
    name: Test and Deploy
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Determine Docker Tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            DOCKER_TAG="${{ inputs.tag }}"
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${{ github.sha }}"
          fi
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "Using Docker tag: $DOCKER_TAG"

      ###############################
      ##           Setup           ##
      ###############################
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup go-task
        run: curl -sSf https://taskfile.dev/install.sh | sh -s -- -b $HOME/.local/bin

      - name: Setup Depot
        uses: depot/setup-action@v1

      ###############################
      ##           Build           ##
      ###############################
      - name: Build and Load Docker image
        uses: depot/build-push-action@v1
        with:
          project: ${{ env.DEPOT_PROJECT_ID }}
          platforms: linux/arm64
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          load: true
          push: false

      - name: Build and Load Docker Testing image
        uses: depot/build-push-action@v1
        with:
          project: ${{ env.DEPOT_PROJECT_ID }}
          platforms: linux/arm64
          context: .
          tags: ${{ env.IMAGE_NAME }}:testing
          load: true
          target: tester
          push: false

      ###############################
      ##         Test Code         ##
      ###############################
      - name: Test Docker image
        run: NO_BUILD=1 IMAGE=${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} TESTING_IMAGE=${{ env.IMAGE_NAME }}:testing task test

      ###############################
      ##        Deploy Code        ##
      ###############################
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
